# Generated by Django 5.2 on 2025-04-29 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Ingrese sus nombres completos', max_length=100)),
                ('apellidos', models.CharField(help_text='Ingrese sus apellidos completos', max_length=100)),
                ('pais', models.CharField(help_text='País de residencia', max_length=50)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('ciudad', models.CharField(help_text='Ciudad de residencia', max_length=50)),
                ('sexo', models.CharField(choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino'), ('OTRO', 'Otro')], max_length=20)),
                ('edad', models.PositiveIntegerField(help_text='Debe ser mayor de 18 años', validators=[django.core.validators.MinValueValidator(18)])),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido. Use números y un + opcional', regex='^\\+?[\\d\\s]{8,15}$')])),
                ('correo_electronico', models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado'}, max_length=254, unique=True)),
                ('estado_emprendimiento', models.CharField(choices=[('AÚN NO INICIO MI EMPRENDIMIENTO', 'Aún no inicio mi emprendimiento'), ('YA INICIÉ MI EMPRENDIMIENTO PERO AÚN NO GENERO UTILIDADES', 'Ya inicié pero sin utilidades'), ('YA INICIÉ MI EMPRENDIMIENTO Y YA GENERO UTILIDADES', 'Ya inicié y con utilidades')], max_length=60)),
                ('rol', models.CharField(choices=[('SOCIO CAPITALISTA', 'Socio capitalista'), ('SOCIO TRABAJADOR', 'Socio trabajador'), ('SOCIO IGUALITARIO (CAPITAL Y TRABAJO)', 'Socio mixto (capital y trabajo)')], max_length=40)),
                ('descripcionProyecto', models.TextField(help_text='Describa su proyecto (máximo 800 caracteres)', max_length=800)),
                ('tipoemprendimiento', models.CharField(blank=True, choices=[('PRODUCTOS', 'Productos'), ('SERVICIOS', 'Servicios')], max_length=20, null=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('opcion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['correo_electronico'], name='email_index')],
            },
        ),
    ]
