# Generated by Django 5.2 on 2025-04-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprendimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50, null=True)),
                ('ciudad', models.CharField(max_length=50, null=True)),
                ('nombres', models.CharField(max_length=100, null=True)),
                ('apellidos', models.CharField(max_length=100, null=True)),
                ('sexo', models.CharField(max_length=10, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('telefono', models.CharField(max_length=15, null=True)),
                ('correo_electronico', models.CharField(max_length=100, null=True)),
                ('estado_emprendimiento', models.CharField(max_length=100, null=True)),
                ('se_centra_en', models.CharField(max_length=50, null=True)),
                ('categoria', models.CharField(max_length=100, null=True)),
                ('opcion_especifica', models.CharField(max_length=255, null=True)),
                ('rol', models.CharField(max_length=100, null=True)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
    ]
