# Generated by Django 5.2 on 2025-04-20 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Ingrese sus nombres completos', max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='Ingrese sus apellidos completos', max_length=100, verbose_name='Apellidos')),
                ('pais', models.CharField(help_text='País de residencia', max_length=50, verbose_name='País')),
                ('ciudad', models.CharField(help_text='Ciudad de residencia', max_length=50, verbose_name='Ciudad')),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=20, verbose_name='Sexo')),
                ('edad', models.IntegerField(help_text='Debe ser mayor de 18 años', validators=[django.core.validators.MinValueValidator(18)], verbose_name='Edad')),
                ('telefono', models.CharField(blank=True, help_text='Número de contacto', max_length=20, null=True, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado'}, max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('estado_emprendimiento', models.CharField(choices=[('NO_INICIADO', 'Aún no inicio mi emprendimiento'), ('INICIADO_SIN_UTILIDADES', 'Ya inicié pero sin utilidades'), ('INICIADO_CON_UTILIDADES', 'Ya inicié y con utilidades')], max_length=100, verbose_name='Estado del Emprendimiento')),
                ('rol', models.CharField(choices=[('CAPITALISTA', 'Socio capitalista'), ('TRABAJADOR', 'Socio trabajador'), ('MIXTO', 'Socio mixto (capital y trabajo)')], max_length=50, verbose_name='Rol en el Emprendimiento')),
                ('descripcionProyecto', models.TextField(help_text='Describa su proyecto en 500 caracteres máximo', verbose_name='Descripción del Proyecto')),
                ('tipoEmprendimiento', models.CharField(blank=True, choices=[('PRODUCTOS', 'Productos'), ('SERVICIOS', 'Servicios')], max_length=50, null=True, verbose_name='Tipo de Emprendimiento')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título/Categoría')),
                ('opcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Opción Específica')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['correo_electronico'], name='email_index')],
            },
        ),
    ]
