# Generated by Django 5.2 on 2025-04-20 01:13

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipoEmprendimiento',
            field=models.CharField(blank=True, null=True, max_length=20),
        ),
        # Añade aquí otros campos faltantes si es necesario
    ]
