# Generated by Django 5.2 on 2025-04-20 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_missing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(help_text='Ingrese sus apellidos completos', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(help_text='Ciudad de residencia', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico',
            field=models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='descripcionProyecto',
            field=models.TextField(help_text='Describa su proyecto (máximo 800 caracteres)', max_length=800),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.PositiveIntegerField(help_text='Debe ser mayor de 18 años', validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado_emprendimiento',
            field=models.CharField(choices=[('AÚN NO INICIO MI EMPRENDIMIENTO', 'Aún no inicio mi emprendimiento'), ('YA INICIÉ MI EMPRENDIMIENTO PERO AÚN NO GENERO UTILIDADES', 'Ya inicié pero sin utilidades'), ('YA INICIÉ MI EMPRENDIMIENTO Y YA GENERO UTILIDADES', 'Ya inicié y con utilidades')], max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(help_text='Ingrese sus nombres completos', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='opcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(help_text='País de residencia', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('SOCIO CAPITALISTA', 'Socio capitalista'), ('SOCIO TRABAJADOR', 'Socio trabajador'), ('SOCIO IGUALITARIO (CAPITAL Y TRABAJO)', 'Socio mixto (capital y trabajo)')], max_length=40),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido. Use números y un + opcional', regex='^\\+?[\\d\\s]{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipoEmprendimiento',
            field=models.CharField(blank=True, choices=[('PRODUCTOS', 'Productos'), ('SERVICIOS', 'Servicios')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
